### ISSUE TITLE
Update MLP-OP DSPEC and run ColdStunning

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#156]

**Comment by bestrada33** [comment]
Fixing bugs with NDFD and the API. Maybe this should have been a separate branch? However, I already committed changes to this branch.

**Comment by bestrada33** [comment]
This does not seem right. fromDateTime and toDateTime do not seem to be getting calculated correctly when trying to run MLP-OP DSPEC


![Image](https://github.com/conrad-blucher-institute/semaphore/assets/74482285/d81c41c5-8db3-426c-9c61-36d08c57bbe2)
