### ISSUE TITLE
Dockers running on Sherlock Dev (Core and DB)

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#159]
Dependent on cron scheduled working

**Comment by bestrada33** [comment]
- Getting this error when trying to run init_db.py inside the container. Maybe networks will come into play?

![Image](https://github.com/conrad-blucher-institute/semaphore/assets/74482285/19db9782-ac2b-4ad3-a97c-414bce3c6170)

- Also, how can we access through pgAdmin? What about the API? Maybe a question for Son.
