### ISSUE TITLE
Compare web and DB predictions

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#185]

**Comment by matdenkas** [comment]
We have not been able to get enough data as Cold Stunning refuses to run correcting for a significant time.

**Comment by ccftissot** [comment]
> We have not been able to get enough data as Cold Stunning refuses to run correcting for a significant time.

Let's move this story out of this milestone.  We should revisit this milestone anyway as it has been past due for too long.
