### ISSUE TITLE
Create Health Check for Semaphore-API

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#188]
To determine if the automated deployment worked, we need a health check from core to read.
(This is a command we run every few seconds defined in the docker-compose see DB configuration)

Possibility:
- https://pypi.org/project/fastapi-healthcheck/
- Hit the API for something?
- Semaphore runner -h

**Comment by lovelysandlonelys** [comment]
Sources Looking At: 
- https://github.com/jtom38/fastapi_healthcheck_uri/blob/master/fastapi_healthcheck_uri/service.py
- https://medium.com/@thkhoobsmart/adding-health-check-to-docker-container-b4eb1d554f36
- https://docs.docker.com/engine/reference/builder/#healthcheck
- https://scoutapm.com/blog/how-to-use-docker-healthcheck
