### ISSUE TITLE
Rewrite cron_init

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#189]
~~We are currently using -r to remove the cron file which is dangerous if there multiple people using the cron file.~~

- ~~Back up cron file before modifying it! [Semaphore + timestamp]~~

~~Possible solutions:~~

- ~~Initializing the cron job in the docker~~
- ~~Find a way to make a private cron file~~
- ~~Add and remove the jobs dynamically~~
- - ~~Own a region of the cron file marked with comments.~~
- ~~Have a single cron job that handles the scheduling~~ 

-Resolved by Semaphore receiving it's own service account on sherlock prod

**Comment by lovelysandlonelys** [comment]
Add comments to cron file itself to explain what each job is for.

**Comment by lovelysandlonelys** [comment]
Notes:
- Add thermal refuge model to cron file
- add comments mentioning the intent of each cron job
