### ISSUE TITLE
MLP-OP Failing consistantly in production

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#200]
This bug can be reproduced by putting the MLP-OP in prod and waiting. It seems to after a while start to mix up inputs.

This bug cannot be reproduced by running the NDFD manually, or through the API, nor can it be reproduced by just running the MLP-OP model manually.

This bug likely is within the NDFD ingestion class or the configuration of its requests to the API, as other Ingestion classes are working fine.

First recommended steps: Improve logging on failure from a data grab:
- When a miss match occurs print the data series and and types.

**Comment by matdenkas** [comment]
Looking at logs, NDFD_EXP is always failing to get inputs at the time. It gets more results than expected, 20 or 21 when expecting 16
Sometimes LIGHTHOUSE fails but that's because the data isn't there.
I can run the model myself and everything works

**Comment by matdenkas** [comment]
I was unable to reproduce on local machine. I added better logging and deployed it to sherlock-dev

**Comment by matdenkas** [comment]
Light house is returning data again

**Comment by matdenkas** [comment]
It seems clear to me that NDFD is changing the data as time goes on. When we pull from NDFD (to get new times) it sends upadted old times, which dont merge with the old times from the DB query thus giving us more predictions than expected

**Comment by ccftissot** [comment]
> It seems clear to me that NDFD is changing the data as time goes on. When we pull from NDFD (to get new times) it sends upadted old times, which dont merge with the old times from the DB query thus giving us more predictions than expected

this is why i don't think we should merge the results.  We know the timestamps we expect for each input and we should query the DB for these and, when some are missing, we should invoke the ingestion class to get more.  When we get the new batch from the ingestion class, we should look for our missing timestamps in the new batch, not just merge the new batch with our result from querying the DB.

**Comment by matdenkas** [comment]
MLP-OP is running successfully
