### ISSUE TITLE
Data base account Follow-up

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#223]
- What permissions would everyone get?
- How do we automatically generate the service accounts?
- How do we script making a human user account?

**Comment by lovelysandlonelys** [comment]
https://docs.google.com/presentation/d/1MrdlKvX5V5iTIBD1l2lXg5pzv_ourT-kv8ftEnGkSfI/edit?usp=sharing

**Comment by lovelysandlonelys** [comment]
biggest complication: creating the users when the database is instantiated. 

testing out making the db container instantiating it's own roles.

**Comment by lovelysandlonelys** [comment]
Meeting Notes 3/29/2024
Research to see if there is a way when using the PostgreSQL container to specify more than one database user credentials as part of the environment variables. 
The other option would be to at the end of making the database write a python script to set up the other user accounts.

**Comment by lovelysandlonelys** [comment]
Notes: 
- we need a strategy for data migration "transactional data migration" and also "metadata data migration" 
- these could potentially be two diff strats
- catiac
- versions of the database and keep track of when you deply and associate with each version you have a script that you can run, and version 1.2 has it's own script that updates 1.0 to bring it up to 1.2. you would do init_db and then run all thoes scripts one at a time to get the database up to date
- poormans
- create scrips that you update and you version in github and run thoes scripts as part of your deplyment. a deploy scrip that runs SQL scrips to add to the database that's already up, and you usually also want a rollback script accociated with the deployment script

We need to decide what we want to do!
- do we want to tackle the data migration issue now or put off making any changes to database

**Comment by lovelysandlonelys** [comment]
- maybe just create a python file that is SOLELY  to create the api account and that's part of the deployment 
- this would be a shortcut
- Matthew: We building technical debt!
- put database account follow up on ice and create new tickets that revolve around creating our strategy for updating and migrating data for the database


- focus on the poormans strategy for now
- come up with a script to add new rows and stuff to the database
- matthew likes the idea of having a table with the version of the database and then automatically 
- okay he making tasks
