### ISSUE TITLE
Adding Marina water level predictions to portal graph

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#230]
Once Marina's water level model is operationalized, we will add her model predictions as a line to the [Portal Page Live Water Level Measurements and Predictions chart](https://www.coastaldynamicslab.org/portal). 

The chart is made by [CBOCP](https://github.com/conrad-blucher-institute/cbocp), the monster of a "web app" that Beto made.

Task will involve:
- Adding an ingestion class (or well file) for Semaphore API in CBOCP
- Formatting output from Semaphore such that it matches the CSV files used in CBOCP
- Merging the formatted output from Semaphore into the CSV file used for the portal chart
- Adding the HighCharts code that will plot the new line
- Testing locally and on sherlock-dev
- Deploying the new changes to sherlock-prod. (You'll get to see how JANK everything is.)

**Comment by bestrada33** [comment]
# To do:
- Interpolate (linear) between now measurement and 12hr pred, then from 12hr pred to 24 hr pred.
- If
