### ISSUE TITLE
Finalize and Test DSPEC Models for magnolia beach

### ISSUE THREAD

**Issue by lovelysandlonelys** [conrad-blucher-institute/semaphore#287]
Notes: 
- Create DSPEC
     - 12h lead time (1st and 2nd)
     - 48h lead time (1st and 2nd)
- Check DSPECs with Jacob final time
- Test if models run locally

**Comment by matdenkas** [comment]
We need to add interpolation commands, and do the other lead times

**Comment by lovelysandlonelys** [comment]
12h Transform Not Working
- speak to
