### ISSUE TITLE
Talk to Jacob about 12hr transform

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#330]
Email jacob about the organization of the 12 hour transform dspec and what its structure is supposed to be

**Comment by lovelysandlonelys** [comment]
Dear Savannah,

Good evening! Thankfully my finals have ended, but I am now beginning my internship so I apologize for the delay in response again. After inspecting my model's architecture, I believe the error is with the variable MG_WL_F12, and as you said, this value is actually taking the current future prediction plus the past 12 hours of future predictions (so 13 total hours). Hopefully this clarification helps to fix the error with the model, and hopefully the predictions for the other models look somewhat ok. Please let me know if any other questions come up and have a wonderful day!

Sincerely,
Jacob Alonzo

**Comment by lovelysandlonelys** [comment]
Team agrees that we should meet with Jacob about this to discuss how to fix this issue as his email explanation is a bit vague.
