### ISSUE TITLE
Investigate Incorrect and duplicated values in the ref_series table in the displayName and notes columns

### ISSUE THREAD

**Issue by ccftissot** [conrad-blucher-institute/semaphore#392]
Both production and dev ref_dataSeries tables are showing the same numerous issues with the values of in the displayName and noes columns (see below).

After fixing these issues, we should add a uniqueness constraint at the very least on the displayName column, as there is no reason to ever have duplicate values and it will avoid the kind of issues we are seeing now.  We also need to discuss issue #3 below as it seems to be a major issue that can affect existing models

Issues:

1. Duplicate and either incorrect values in the displayName column: e.g.,  'Water Temperature' value appears 4 times, 2 of which to describe air temperature :-(
2. Not distinguishing between predictions and measurements in the displayName column
3. The 12 series storing mean calculations:  we should discuss why we are storing calculated values.  And we need to give each a unique display name.

**Comment by matdenkas** [comment]
https://docs.google.com/spreadsheets/d/1vse3ADuG75BQ2kK78LOTe8_1hG-NW8X4XA9PJwSvJ64/edit?usp=sharing

Here is a exel sheet with the proposed DB changes and the files/DSPECS that will be effected

**Comment by matdenkas** [comment]
**Refactor plan**
1. Create DB Migration scrip to update DB information as detailed in the above spreadsheet.
2. Create a PPC (post processing class) for 4 max mean.
3. Refactor MLP-OP to fix broken reference
4. Update (ar, nj, pi, rp)_mlp_(12h, 24h, 72h) models and ar_inundation_(jan, feb, mar,...)  models to 2.0 using the updated dspec version
5. Refactor test_API, test_NOAATANDC, test_dspec, NDBC, NOATANDC files to fix broken references to changed DB information

**Comment by lovelysandlonelys** [comment]
08-23-2024 Meeting Notes: 

split into two stories: one migration just to fix the display names that are wrong, another to fix the issue of soring calculated values

prioratize what models need to be moved up to 2.0

refactor NDFD to pull lon and lat from the data_location_source_mapping rather than directly referencing the location table
