### ISSUE TITLE
Prioritize What Models need to be moved to 2.0 DSPEC

### ISSUE THREAD

**Issue by lovelysandlonelys** [conrad-blucher-institute/semaphore#417]

**Comment by matdenkas** [comment]
![Image](https://github.com/user-attachments/assets/473903a0-f165-465f-934d-2f51dc26075b)
https://docs.google.com/spreadsheets/d/1eV9fRGkZnrJYPFxOCErO9p_oEVL2Mu1whJM-uyYW-30/edit?usp=sharing
