### ISSUE TITLE
Stop Inserting Data into the Database from the API

### ISSUE THREAD

**Issue by lovelysandlonelys** [conrad-blucher-institute/semaphore#480]
Stop inserting data into the database when requesting inputs from the API.

**Comment by matdenkas** [comment]
Series provider should have a flag on request Series on which to choose if we ever insert into the database. This flag should be assumed True and set false by the API

**Comment by matdenkas** [comment]
This work was done in [PR#482](https://github.com/conrad-blucher-institute/semaphore/pull/482)
