### ISSUE TITLE
Research API tech and develop plan to implamnet

### ISSUE THREAD

**Issue by bestrada33** [conrad-blucher-institute/semaphore#60]
- Add 2 endpoints: outputs and Semaphore predictions
- Add proper documentation

**Comment by matdenkas** [comment]
We will need to refactor the description objects, and probably standardize them into one object for a cleaner api implementation

**Comment by bestrada33** [comment]
To run:

- Make sure your environment is activated! `source ./venv/vsem/Scripts/activate`
- `pip install -r requirements.txt` to install new dependencies
- From the root directory run `uvicorn src.API.main:app`
- You can specify `--host` and `--port` if you so desire
- uvicorn will give you a link to the index page of the API. Add `/docs` to the URL to access the docs page
