### ISSUE TITLE
BUG with lead time and time generated calculation

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/semaphore#69]

**Comment by matdenkas** [comment]
Add lead time to seriesDescription object and make sure prediction tables are quering on lead time!

Bug fix to check and make sure this can actually work. Its throwing some op error on the time generated and lead time calculation

**Comment by lovelysandlonelys** [comment]
code for demo file to test/find error

##run_test(True)
from DataClasses import SemaphoreSeriesDescription
s = SemaphoreSeriesDescription('test AI', '1.0.0', 'waterHeight', 'packChan', 3600, 24, 'test_datum') 
s.toDateTime = datetime.combine(date(2023, 9, 5), time(11, 0))
s.fromeDateTime = datetime.combine(date(2023, 9, 5), time(11, 0))
from SeriesProvider.SeriesProvider import SeriesProvider
seriesProvider = SeriesProvider()
result = seriesProvider.make_output_request(s)
print(result)
print(result.data)
