### ISSUE TITLE
Research NDFD

### ISSUE THREAD

**Issue by snguyen1** [conrad-blucher-institute/semaphore#82]
- Research generated time solutions
- Research lat/lon coordinates and how to get them from the db to the url_creator using location name
- Make units metric by default
- Extract unit name from NDFD data for series object

**Comment by bestrada33** [comment]
- Philippe says to use the time acquired as the generated time for now until Waylon responds to the email
- Will need to calculate the lead time with this approach

**Comment by bestrada33** [comment]
Check on tz for UTC
