### ISSUE TITLE
Develop Entry-Point for Semaphore

### ISSUE THREAD

**Issue by snguyen1** [conrad-blucher-institute/semaphore#84]
Why: We need an entry point to support the final design.
Big picture: Semaphore will be containerized and this file is the only way to trigger the semaphore python code via command line.

TODO: This file will need to receive and read arguments/parameters.
Example: `python3 semaphore_runner.py arg1 arg2 arg3 ....`

For each argument, we will need to declare the format and a description. 

*Note:  Be careful when passing string with special or escape characters ( `\` `/`).
Create validation and handle errors if the format is not correct (example: wrong date time format....)

Needs to **document** the arguments in the `README.md` file once that's done so visitor knows how to run the code

**Comment by lovelysandlonelys** [comment]
-make folder with command title

-make semaphore_runner.py

-use code that matthew sent as a guide for writing a command line with [[demo.py](http://demo.py/)](http://demo.py) that takes a dspec name and a time to run semephore from terminal

**Comment by lovelysandlonelys** [comment]
current argument ideas

name of dspec file

time that semaphore needs to run, the reference time that semaphore uses to decide the range of time that semaphore grabs data from

**Comment by matdenkas** [comment]
When this ticket is reelected, discuss what arguments exactly and how to validate them.

**Comment by matdenkas** [comment]
FileName: str -> The name of the DSPEC file to run
ReferenceTime -> 
ExecutionTime ->

**Comment by lovelysandlonelys** [comment]
ARGUMENTS
1) dspec filename
- Validate that the file exists using the method inputGatherer.py lines 49 - 54 (checking that a true path is constructed)
2) execution time
- a optional argument that you can provide to run in the past/ otherwise runs in present
- needs to be formatted in the correct way
- throw an error if the time is in the future
