### ISSUE TITLE
Plan on refactoring prediction table

### ISSUE THREAD

**Issue by snguyen1** [conrad-blucher-institute/semaphore#85]
We should be storing data points not series

**Comment by matdenkas** [comment]
![Image](https://github.com/conrad-blucher-institute/semaphore/assets/64288827/bae99168-a7ae-4661-915f-f5efc519c330)

**Comment by matdenkas** [comment]
![Image](https://github.com/conrad-blucher-institute/semaphore/assets/64288827/b4b8f816-7e83-4dbd-ad72-03ea87160771)

**Comment by matdenkas** [comment]
![Image](https://github.com/conrad-blucher-institute/semaphore/assets/64288827/d5cf6585-c967-440a-8581-da028173ee43)
