### ISSUE TITLE
Refactor s_prediction_selection in SQLLite.py to not request lead time from SeriesDescription

### ISSUE THREAD

**Issue by bestrada33** [conrad-blucher-institute/semaphore#86]
s_prediction_selection currently ask for leadTime from a seriesDescription, which doesn't exist.

**Comment by bestrada33** [comment]
I'm thinking the best option is to just add `leadTime` as an optional argument to `SeriesDescription`. 

- Looking to see where instances of `SeriesDescription` are created, `inputGatherer` seems to have one. Would just need to explicitly map the member variables
- `apiDriver.py` also has one. Would need to do the same as above.

**Comment by matdenkas** [comment]
A lot of this will change after the refactor, but one thing to keep in mind is we could have three coastal inundation models, all predicting the same thing at the same time. The only difference is the lead time of the model. Plus its name and stuff. Maybe this wont spread to the ouput table
